### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ajitam** [sledilnik/website#1028]
Any plans for dark theme?
I use "Dark Reader" which is quite good at its job, but on Sledilnik.. not so good :) 

![image](https://user-images.githubusercontent.com/672661/152426774-8e461df9-42fc-43a6-a84e-584e3afcfd76.png)

**Comment by stefanb** [comment]
Don't use dark reader then? 😄
Alternatively, we could accept a PR with a dark theme if there's interest for that.

**Comment by stefanb** [comment]
Why is dark reader changing fonts?

**Comment by ajitam** [comment]
regarding font - this is just a "additional rule"
everything else is "out of the box"

I'm closing this now - sorry for nagging - I just thought that maybe dark mode was somewhere in the pipeline.

**Comment by mojca** [comment]
I would love to see dark theme too ...
