### ISSUE TITLE
UX: Zemljevid: dodati graf rasti za občino

### ISSUE THREAD

**Issue by matejmeglic** [sledilnik/website#105]
- dodati % od dejanskega prebivalca poleg primerjave Okuženih na 100k 
- dodati graf Okuženih po občini na on_hover z rastjo potrjeno okuženih in s časom podvojitve (mal me skrbi response time, če se bodo morali grafi generirat on_the_fly na mobilu)
![image](https://user-images.githubusercontent.com/26248400/78046218-2c508b80-7377-11ea-9c94-4b128c5a7f51.png)

**Comment by lukarenko** [comment]
% okuženih smo dali že v #152 - tole je samo za dodajanje grafka

**Comment by lukarenko** [comment]
Tole se ne da enostavno, zato ne bomo delali.
