### ISSUE TITLE
Povezave - re:order

### ISSUE THREAD

**Issue by Multicultivator** [sledilnik/website#111]
Nova grupacija /Povezave, z dodano sekcijo "Modeli"; 
vidnih zgolj "top 5", ostalo na klik...

- Slovenija /-> Podatki in Statistike / Vizualizacije / Modeli / Razno

- Svet  /-> Podatki in Statistike / Vizualizacije / Modeli / Razno

https://slo-covid-19.slack.com/archives/C010R8UF077/p1585311696019600
1:22
V "Povezave" naredimo dva glavna sklopa - Slovenija in Svet ?
1:23
V vsakem sklopu naredimo nekaj pod-sklopov glede na vsebino: Podatki in Statistike / Vizualizacije / Modeli / Razno

**Comment by Multicultivator** [comment]
TABELA v dropdownu : 

 To je neka tabela...pred dropdownom
| Vlada      |     | Ostale službe|
|:----------:|:---:| --------------------------:|
| git status |     | git status                 |
| git diff   |     | git diff                   |
<details>                   
<summary>Več.....</summary>

 To je neka tabela...v dropdownu
| Vlada      |     | Ostale službeRight-aligned |
|:----------:|:---:| --------------------------:|
| git status |     | git status                 |
| git diff   |     | git diff                   |

</details>

**Comment by umarovt** [comment]
Done. Zapiram ticket.
