### ISSUE TITLE
Anchors on front_page

### ISSUE THREAD

**Issue by matejmeglic** [sledilnik/website#116]
Prosil bi, da še enkrat pogledamo, če se na posamezni graf da dodati anchor (focus), da lahko potem te linke uporabimo za social in za detaljna navodila posameznikom, kaj naj gledajo.

**Comment by overlordtm** [comment]
Relevantna koda je 

Za scrollTo ob navigaciji po strani
https://github.com/slo-covid-19/website/blob/master/src/index.js#L89

Za scrollTo ob initial loadu strani (F5 refresh)
https://github.com/slo-covid-19/website/blob/master/src/App.vue#L34

**Comment by VesterDe** [comment]
@overlordtm Data fetching je tricky, ker nimamo callbacka za ko se vsi zgodijo... Ampak tale koda je za mene 98% zanesljiva:

```
const potentialChartAnchor = window.location.hash.split('#').pop()
      setTimeout(() => {
        document.getElementById(potentialChartAnchor).scrollIntoView({ behavior: 'smooth', block: 'center' })
      }, 3000)
```

**Comment by lukarenko** [comment]
@overlordtm a si uspel pogledat tale predlog hacka od @VesterDe ?

**Comment by lukarenko** [comment]
PR: https://github.com/slo-covid-19/website/pull/138

**Comment by umarovt** [comment]
Zapiram ticket, ker bo resen z prestavitvijo infrastrukture na Hetzner in odstranitvijo # iz URL-ja.

**Comment by lukarenko** [comment]
For now this is it. We could improve them, but this is for separate issue.
