### ISSUE TITLE
UX: Tooltips za "Širjenje COVID-19 v Sloveniji" labele pod grafom

### ISSUE THREAD

**Issue by tomazk** [sledilnik/website#157]
Izboljšali smo labele pod grafom "Širjenje COVID-19 v Sloveniji" ampak nekatere stvari so še vedno dvoumne, zato bo potrebovali še mobile & desktop friendly tooltips.

![FireShot Capture 013 - Sledilnik – Figma - www figma com](https://user-images.githubusercontent.com/83787/78498643-cc2d6100-774b-11ea-976b-28bb47ccda04.png)

Vse je dokumentirano v tem dokumentu:
https://docs.google.com/document/d/1kqcwR8OfhcWNknCLzkJaqw_uy4QQ76PWf9Bsa9F5Eyo/edit?usp=sharing

**Comment by lukarenko** [comment]
we have decided for simplier split of metrics so not relevant anymore
