### ISSUE TITLE
Vizualizacija - trend-  pri prikazu naredimo ‘napoved’ za naslednjih nekaj dni (eg 4) 

### ISSUE THREAD

**Issue by matejmeglic** [sledilnik/website#22]
Predlog za vizualizacijo trenda: pri prikazu naredimo  ‘napoved’ za naslednjih nekaj dni (eg 4) tako da preprosto fitamo eksponentno funkcijo na zadnjih nekaj data pointov (eg 4)
Benefits:
- javnost vidi, ali smo ze obrnili krivuljo ali ne
- javnost vidi, kaj je za pricakovat v naslednjih dneh
- model je zelo lokalen, ni treba napovedovat dogajanja cez velike casovne intervale
ker je samo 4 dni ekstrapolacije (napovedi), so nedoločenosti napovedi relativno majhne
- če pokažemo da bi s takim pristopom zadnji teden pravilno napovedal nove številke za naslednji dan, potem povečujemo zaupanje javnosti v modeliranje na splošno (nekako tako kot delajo meteorologi)
- s tem potgnemo vzporednico temu kar kaže vlada, ampak data-driven in proper

Več: https://slo-covid-19.slack.com/archives/C01056ZMG3S/p1584780242061500

**Comment by umarovt** [comment]
Model je pripravljavljen, vendar ker zaenkrat to ne bi bilo dovolj natancno/informativno zaenkrat ne bomo objavili. Zapiram ticket.
