### ISSUE TITLE
InfectionsChart: na prvi graf lahko dodamo nazaj prikaz faz 1-5 (plotBands/plotLines)

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/website#228]
Na InfectionsChart lahko popravimo da bo na SplineChart kazal faze (plotBands/plotLines).

Na bar chartih smo jih skrili, ker se niso videli, samo sedaj imamo spet Splinechart, jih pa lahko kažemo.

**Comment by breki** [comment]
Done
