### ISSUE TITLE
UX: check/uncheck all gumbi za MetricsComparison/Regions

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/website#230]
Rabili bi enostavna Izberi vse (Check All) / Počisti vse (Uncheck All) gumba za grafe, kjer ročno izbiraš posamezne metrike: MetricsComparison, Regions

Primer implementacije je tukaj:
http://jsfiddle.net/simo/57SR9/94/

Najbolje bi bilo, če bi imeli za ta dva gumba ikono + tooltip tekst, zato da ne zavzemata preveč prostora.

**Comment by umarovt** [comment]
Še en predlog.

https://dribbble.com/shots/6182239-Report-Builder-for-NLP-Platform

**Comment by lukarenko** [comment]
We have split metrics for first chart and have all on for second, so this is less relevant and would just clutter mobile UI (60+% users)
