### ISSUE TITLE
Podvojitev: barvna skala?

### ISSUE THREAD

**Issue by matejmeglic** [sledilnik/website#27]
Podobna vizualizacija je mogoče Graf za občine  https://slo-covid-19.slack.com/archives/C01056ZMG3S/p1585029026191900

**Comment by lukarenko** [comment]
Tole je sedaj že super, manjka samo še, da označimo stolpec dneva X dni nazaj, od kje se zadeva podvoji.

![image](https://user-images.githubusercontent.com/46861689/77876134-64aa7980-7252-11ea-9a78-5ae97538528b.png)

Primer iz originalnega primera:
![image](https://user-images.githubusercontent.com/46861689/77876331-ebf7ed00-7252-11ea-829e-f42bf03e982e.png)

Mislim da ni potrebno da gremo na tako očitno barvo, je pa fajn, če je asociacija med tekstom X dni in stolpcom od kdaj je ponovitev.

**Comment by joahim** [comment]
Our World in Data je med tem že spremenil vizualizacijo, ki trenutno zgleda takole. S tem bi rad opozoril, da prikaz podvojitve intervala na grafu pogosto ni možen, saj je  je daljši od števil dni, za katere so na voljo podatki. Mislim, tudi, da je bi bilo za razumevanje potrebna dodatna razlaga saj povezava ni nujno očitna.

Super bi bilo, če doubling time labele barvno kodiramo. Jure ima vse informacije in čakamo na barve.

<img width="641" alt="Screen Shot 2020-03-30 at 11 57 46" src="https://user-images.githubusercontent.com/1205595/77900087-cdf3b200-727d-11ea-8175-7c84732da747.png">

**Comment by mkadunc** [comment]
Še slikca histograma in predlog za barve (iz threada na #dataviz https://slo-covid-19.slack.com/archives/C01056ZMG3S/p1585503309067900?thread_ts=1585487258.043400&cid=C01056ZMG3S ):

Če damo 4 barve pride cca. 15 občin na barvo, torej:
[0..4] : rdeča1
[5..6] : rdeča2
[7..9] : rdeča3
[10..∞): rdeča4

![histogram_obcine](https://user-images.githubusercontent.com/10532824/77930404-22f9ed00-72ab-11ea-933e-b0f7a7e30b04.png)

**Comment by lukarenko** [comment]
Podvojitev imamo sedaj na grafu, za marker za dan od kdaj se podvoji se tudi strinjamo, da ga ne damo gor. Edina odprta zadeva je, da bi ta `X dneh` ustrezno pobravali (rumeno?), da se ločijo.
Jure: poglej zgoraj z rdečo, kako barvajo lestvico. Zdi se mi, da bi morali biti vsi do 7-14 dni v barvni lestvici, nad 14 pa so lahko sivi.

**Comment by umarovt** [comment]
Trenutno podvojitve niso toliko aktualne, ker se stanje umirja, zato menim, da lahko ohranimo trenutno implementacijo in prikaz. Zapiram ticket.
