### ISSUE TITLE
IE11: latest data boxes keep loading indefinitely

### ISSUE THREAD

**Issue by stefanb** [sledilnik/website#284]
In IE11 the latest data boxes never load
![image](https://user-images.githubusercontent.com/319826/81380431-3189be80-910b-11ea-8716-00bd12a7629d.png)

It is above-the-fold content, the first thing that visitors would see.

**Comment by lukarenko** [comment]
this was fixed, right

**Comment by stefanb** [comment]
Yes, this was fixed with https://github.com/sledilnik/website/pull/285
