### ISSUE TITLE
Dodati razlage ob grafe (potrebujemo text in implementacijo)

### ISSUE THREAD

**Issue by matejmeglic** [sledilnik/website#33]

**Comment by matejmeglic** [comment]
Za @Multicultivator :
Moji predlogi, kje naj se pokaže ikona i:
- Pojasnilo linearnega in logaritmičnega prikaza y osi (skala)
- Potrjeno okuženi po občinah (kako se meri, opisana oba sorta max_cases in fastest_growth)
- Opis grafa podvojitev novih potrjenih okuženih na dan
- Ko Demjan zaključi migracijo strani podatki iz gSheets v nek pregled, potrebujemo opise posameznih stolcev, kjer je potrebno.

**Comment by Multicultivator** [comment]
Working document je na https://docs.google.com/spreadsheets/d/1C7TOwSFwUPJVh-QJVQxt9rccbAxTborkqJVkbqP_i4w/edit#gid=0, 
ko smo blizu implementacije spimpamo, damo na #general v preview in....?

**Comment by matejmeglic** [comment]
zadnja razprava: https://slo-covid-19.slack.com/archives/C01056ZMG3S/p1585664162120200

**Comment by umarovt** [comment]
Določe stvari so že narejene, določene pa bodo v prihodnjih dneh/tednih. Zapiram ticket in ga bom razdlelil v več manjših oz. dodal vsebino drugim ticketom.
