### ISSUE TITLE
Cluttered containment measures baloons in charts

### ISSUE THREAD

**Issue by stefanb** [sledilnik/website#333]
In some cases, when the events are very dense there are 2 baloons for the same event, but they are far apart, the upper balloon pointing to a lower baloon of a different event, eg:

![image](https://user-images.githubusercontent.com/319826/82505571-5c5a1680-9afe-11ea-9dff-26816970013e.png)

In this case they both point to April 17th, but the upper baloon more prominently points to "Servisi" lower baloon instead being visually related to "Vikendi".

**Comment by lukarenko** [comment]
not sure if we can do much, beside having less flags... This is completely done by Highcharts and we have no control.

**Comment by breki** [comment]
Closing this one as I don't really see a way to resolve it. Feel free to reopen it if becomes relevant again.
