### ISSUE TITLE
Dolgo nalaganje in neodziven script chunk-common.js

### ISSUE THREAD

**Issue by dejanmeznarc** [sledilnik/website#411]
Na mobilnem Firefox-u po dolgem nalaganju strani (20 - 50 sekund) dobim spodnje opozorilo, namizna verzija dela brez problema.

Stop script preneha nalagati podatke / zamrzne scroll; pri kliku na continue stran deluje.

Drugače pa super zadevca.

<img width="250px" src="https://user-images.githubusercontent.com/51133739/86496037-de835f00-bd7b-11ea-8004-a55d70c635a9.jpg">

**Comment by breki** [comment]
Probably not relevant anymore since there was quite a bit of work lately on performance improvements.
