### ISSUE TITLE
Negativna stevila okuzenih

### ISSUE THREAD

**Issue by mojca** [sledilnik/website#415]
Tule nekaj ne stima:
![image](https://user-images.githubusercontent.com/15606/86511234-622e6180-bdf7-11ea-94dc-1c5bb14de1b6.png)

**Comment by mkadunc** [comment]
https://twitter.com/_hannahritchie/status/1278991659083214848

**Comment by breki** [comment]
![image](https://user-images.githubusercontent.com/226863/86519625-c0316800-be3c-11ea-8352-94c0bd66e3c3.png)

Source: https://pr-413.sledilnik.org/sl/stats

**Comment by lukarenko** [comment]
This happens when some countries change historical data - the OurWorldInData data set gets nagtive delta. Nothing to do.
