### ISSUE TITLE
Croatian date format

### ISSUE THREAD

**Issue by milotype** [sledilnik/website#416]
Please check the representation of Croatian date formats, in order to get correct form of months.
Currently, the months are shown in their nominativ case, but they need to be in genetive case.

Example 1 - currently:
Aktualizirano: subota, 4. **srpanj** 2020. 10:05

should be 
Aktualizirano: subota, 4. **srpnja** 2020. 10:05

Example 2 - currently:
petak, 3. **srpanj**

should be
petak, 3. **srpnja**

**Comment by stefanb** [comment]
Having the date after the colon makes it less critical as it is not read as a whole sentence, but a separate piece of data.

If we'd want to make that read like a fluid sentence we'd likely also have to fix day names ("u subotu"?) and other languages (Slovenian at least).

We can check if there's an easy way to fix that. Currently we're using the default date formatting in nominative form.

Is that a blocker for Croatian translation?

**Comment by milotype** [comment]
From a pure linguistic point of view – yes, it is a blocker.
From a technical point of view, it could be released as is, but **SHOULD BE** corrected as soon as possible.

Croatian generally uses the "genetiv" form for date strings in the form of:
`4. srpnja 2020.`

The nominative form, like `srpanj` or `Srpanj` (lower case or upper case) is only acceptable when naming the month by itself on a calendar's page header.

BTW, please let me know, where/how is the string `src/locales/hr.json, string 45` used (and other month names). Currently, I have translated them in genetiv form.

Cheers,
Milo

**Comment by breki** [comment]
I agree with @milotype, "4. srpanj" is weird sounding in Croatian. See https://hr.wikipedia.org/wiki/4._srpnja

**Comment by milotype** [comment]
Actually it's not weird, but it is simply wrong in Croatian …

**Comment by stefanb** [comment]
@miaerbus changed nominative month names in croatian to genitive in https://github.com/sledilnik/website/pull/414. 
Please check it at https://pr-414.sledilnik.org/hr/stats

**Comment by milotype** [comment]
Yes, thank you. It looks good!

Milo

**Comment by stefanb** [comment]
Fixed in #414
