### ISSUE TITLE
Croatian and German translations

### ISSUE THREAD

**Issue by milotype** [sledilnik/website#438]
I am a biligual native speaker – Croatian and German. I have completed both languages on Weblate. Please review, and if there are no objections, release both languages.

**Comment by stefanb** [comment]
Hooray!
Can you also prepare a short text for the static pages, `*_de.md` files, similar as in #414, please?

**Comment by stefanb** [comment]
Status of German translation: [![Stanje prevoda](https://hosted.weblate.org/widgets/sledilnik/de/website/svg-badge.svg)](https://hosted.weblate.org/engage/sledilnik/de/?utm_source=widget)

**Comment by stefanb** [comment]
I have updated the all languages preview branch (in #341), which should be redeployed for preview at https://pr-341.sledilnik.org/de/stats in a few minutes.

**Comment by milotype** [comment]
Where should I send the German files for static pages?
I could make a fork on GitHub, add the files in my branch and then send a PR. Please let me know which sledilnik's branch I should use for that (master, or some other).

**Comment by milotype** [comment]
If you want, you can also do it yourself. The text would be (this one is for the About page):

Leider ist diese Seite noch nicht übersetzt. Siehe den [Originaltext in slowenischer Sprache](/sl/about) oder die [englische Übersetzung](/en/about).

Hilf uns diese Seite zu übersetzen [auf GitHub](https://github.com/sledilnik/website/blob/master/src/content/about_de.md).

**Comment by stefanb** [comment]
Great, i will use this text to prepare the PR for German, similar to Croatian!

**Comment by milotype** [comment]
Just to inform you. I've made some minor changes on both languages on Weblate. IMO, they should be final now.

**Comment by stefanb** [comment]
* Croatian: https://pr-414.sledilnik.org/
* Croatian + German: https://pr-443.sledilnik.org/

**Comment by stefanb** [comment]
@milotype,there was a new page added today via #413: https://covid-19.sledilnik.org/sl/world

It contains 2 new charts, requiring some new translations.
🤷‍♂️

**Comment by milotype** [comment]
Can you please check hr and de. I've just translated some new German strings, but there are no new Croatian strings on Weblate to translate!? What am I missing?

**Comment by stefanb** [comment]
It could be that @breki already added all Croatian translations while developing the charts in #413. He for sure added many: https://github.com/sledilnik/website/commit/dfbe89a0c602b7082f797efdb855e94db682fd07#diff-cbcf67a4d8e71f960bf8fc5078d9ef20

 @milotype, please check them for consistency with your translations.

**Comment by stefanb** [comment]
@milotype, I have just updated
- https://pr-443.sledilnik.org/de/world
- https://pr-443.sledilnik.org/hr/world

So you can review translations also there.

**Comment by breki** [comment]
Mostly I just reorganized the existing ones so they work with the new World
page. I added just a few new ones.

**Comment by milotype** [comment]
OK. I've just reviewed hr and de, and made some minor adjustments.

**Comment by milotype** [comment]
sorry ... and some more for hr ... that should be final now (I hope!) 🤔
