### ISSUE TITLE
MetricsComparison: 7 day moving average

### ISSUE THREAD

**Issue by breki** [sledilnik/website#581]

**Comment by breki** [comment]
@lukarenko what exactly should be done here?

**Comment by mkadunc** [comment]
Add an option ‘7d’ in addition to & on the same level as ‘daily’ / ‘active’ / ‘cumulative’.

When selected, the charts would show the same data as ‘daily’, but summed up over the last 7 days.

**Comment by breki** [comment]
The feature was implemented, we still need translations for the new button (`charts.metricsComparison.show7DaysAverage`)
