### ISSUE TITLE
Regions plot - add switch for relative per 100k

### ISSUE THREAD

**Issue by breki** [sledilnik/website#583]

**Comment by lukarenko** [comment]
A nimamo to že z Delež prebivalstva? Lahko dodamo še ta podatek na tooltip, sicer pa ne vem kaj bi morali tukaj narediti?

**Comment by breki** [comment]
> A nimamo to že z Delež prebivalstva? Lahko dodamo še ta podatek na tooltip, sicer pa ne vem kaj bi morali tukaj narediti?

Vprašanje za @mkadunc, tale ticket je iz tistega slack threada:

> 7. Graf Primeri po regijah - možnost za preklop na prikaz "relativno - na 100k prebivalcev"

**Comment by mkadunc** [comment]
Gre za _graf_ primerov po času, ne zemljevid - tam nimamo prikaza glede na prebivalstvo, niti kakega drugega relativnega prikaza.

**Comment by lukarenko** [comment]
A če bi dali podobne grafke kot imamo za občine? To je zelo malo za dodati

**Comment by mkadunc** [comment]
Ne, GRAF in ne ZEMLJEVID

![9E06473D-AFB2-41F0-9C01-0C95461E652B](https://user-images.githubusercontent.com/10532824/95952375-42e0a080-0df8-11eb-94b6-adc82315efd5.jpeg)

**Comment by mkadunc** [comment]
Jaz bi krivulje na zgornji sliki tako, da je Y os utežena na št. prebivalcev

**Comment by lukarenko** [comment]
@mkadunc razmišljam ali bi bil to še en preklopnik: Absolutno Delež prebivalstva ali pa bi to imel samo na Aktivni primeri in dodamo še eno opcijo Aktivni na 100k?

**Comment by breki** [comment]
Kako pa vpliva ta ideja glede upravnih enot? Mogoče bi vse skupaj združili (preklopi po regijah/UE in absolutno/na 100k).

**Comment by lukarenko** [comment]
ja, to bi verjetno tudi dodali, samo potem je že veliko preklopnikov

**Comment by lukarenko** [comment]
This is considered closed
