### ISSUE TITLE
Age groups chart not showing the correct data

### ISSUE THREAD

**Issue by breki** [sledilnik/website#592]
At least with deaths, the total number is lower than the current number of deaths. Not sure about infections. This needs to be investigated.

**Comment by lukarenko** [comment]
Not a bug, but data missing. Nothing to do

**Comment by breki** [comment]
Maybe we should have a warning text next to the chart? @Multicultivator

**Comment by breki** [comment]
To be fixed when #593 is implemented.

**Comment by breki** [comment]
Fixed by adding a disclaimer in #593
