### ISSUE TITLE
Municipality Map's Yesterday view misleadingly displays day before yesterday's data if yesterday's data is not available yet

### ISSUE THREAD

**Issue by matejdro** [sledilnik/website#622]
When new data for the yesterday's cases is not available yet, Municipality Map will misleadingly display older data in the Yesterday view, even though there is no actual data yet. There is no warning or message anywhere that data is actually not from yesterday.

Yesterday View should be disabled (grayed out) or renamed to "Day before yesterday" until data is available.

**Comment by lukarenko** [comment]
We have now added Date info in bottom left corner and renamed misleading Yesterday to 1 day
