### ISSUE TITLE
Municipality chart bars not rendered

### ISSUE THREAD

**Issue by lukarenko** [sledilnik/website#631]
As of today, several municipalities do not get rendered bars
![image](https://user-images.githubusercontent.com/46861689/96609456-d5060e80-12fa-11eb-8c24-22140e73e04a.png)

Data is there, as seen in tooltip:
![image](https://user-images.githubusercontent.com/46861689/96609520-e7804800-12fa-11eb-892a-6ce23e832d5d.png)

Or in All mode:
![image](https://user-images.githubusercontent.com/46861689/96609588-f535cd80-12fa-11eb-9c62-69e28661ed3e.png)

**Comment by miaerbus** [comment]
Fixed by @joahim
