### ISSUE TITLE
Chart "Primerjava po dnevih v tednu" has Dead in wrong column

### ISSUE THREAD

**Issue by th0r88** [sledilnik/website#696]
**Env:** local/prod

**Device:** MacBook Pro 16", macOS 10.5.7, Google Chrome Version 86.0.4240.193 (Official Build) (x86_64)

**Expected:**

Column Dead (Umrli) is representing data for the same day that is reported.

**Actual:** 

Column Dead shows yesterday data for today:

<img width="1106" alt="Screenshot_2020-11-18_at_17_17_26" src="https://user-images.githubusercontent.com/10115360/99561183-fbd16680-29c6-11eb-8b8a-2ce63229d31a.png">

<img width="352" alt="Screenshot_2020-11-18_at_17_17_37" src="https://user-images.githubusercontent.com/10115360/99561197-ff64ed80-29c6-11eb-84c9-4881ff1ceb4a.png">

**Comment by lukarenko** [comment]
Sorry, this is cause by data about deaths (from hospitals) being at 8:00, while we calculate active cases for last datapoint of confirmed cases (midnight). Really not sure if we can do anything better here.

**Comment by lukarenko** [comment]
Nothing to do
