### ISSUE TITLE
Graph "Stanje COVID-19 v Sloveniji", missing units on y-axis

### ISSUE THREAD

**Issue by AntoJurko** [sledilnik/website#740]
I see this only on my Android mobile phone: Mi A1, Android 9, update from 1.8.2020.
Web site is opened using Chrome.

Windows Chrome and Edge are ok.

Update: Got the same issue on anoter phone: Remi Note 3, Android 6.0.1 MMB29M

**Comment by lukarenko** [comment]
Screenshot please

**Comment by AntoJurko** [comment]
I have problems to transfer screenshots from a mobile. This cut off is done on Win Chrome, units on the right side are missing. 
![missing units](https://user-images.githubusercontent.com/587975/101359175-3169c100-389c-11eb-9c9b-b57f5ee77eaa.PNG)

The next graph "Primerjava po dnevih..." has them, graphs (Hospitalizirani, Neg. bolnišnice, Umrli) do not. 
Graph "Presežne smrti" ok.

I'll clear everything to see if that helps

**Comment by AntoJurko** [comment]
Screenshots:
![Screenshot_20201207-144046](https://user-images.githubusercontent.com/587975/101376466-e8703780-38b0-11eb-8da0-9b7e31a03643.png)
![Screenshot_20201207-144058](https://user-images.githubusercontent.com/587975/101376460-e6a67400-38b0-11eb-8c7d-876d2d8ef459.png)

**Comment by lukarenko** [comment]
Oh, bug is actually on daily comparison chart - on mobile (<768 screen) we should always hide Y axis labels.

**Comment by lukarenko** [comment]
Fixed, by removing yAxis label on all charts on small screens

**Comment by AntoJurko** [comment]
Checked, ok.
