### ISSUE TITLE
Add "Confirmed PCR Cases" option to "Comparison by Day of Week"

### ISSUE THREAD

**Issue by matejdro** [sledilnik/website#775]
Last week HAT tests have been added to Sledilnik page. This consequently broke "Comparison by Day of Week" chart. 

Whole point of this chart is that we can compare the current numbers to the past numbers. However, since confirmed cases number now also includes HAT tests, numbers are not comparable to the numbers of the past week anymore, since those numbers only included PCR tests (new numbers will always be higher due to HAT tests. If we performed HAT tests in the previous weeks, numbers would likely be similarly higher, but we didn't, so we can't really compare those numbers).

Good solution to this issue would be to add separate option to that chart that would only compare PCR cases to the previous days instead of combined case numbers.

**Comment by lukarenko** [comment]
But this was also true with any change of test methodology in past. Not sure if adding split confirmed cases would really help.
Maybe we should indicate when methodology have changed also on this chart, but not really sure how this can be done...

**Comment by matejdro** [comment]
Sure, but with previous changed of testing methodology you couldn't really do anything, you simply didn't have the numbers with old methodology anymore. But with this change you still have the old numbers (AFAIK PCR tests methodology has not been changed).

**Comment by lukarenko** [comment]
Adding HAT is similar change as any change in testing methodology in past. We present those on main chart as vertical lines and describe them in the [FAQ:](https://covid-19.sledilnik.org/sl/faq#chart-phases)
![image](https://user-images.githubusercontent.com/46861689/103336341-2b6c9780-4a78-11eb-89f4-19d8c07d0a4c.png)

**Comment by matejdro** [comment]
I would argue that it is NOT similar change. Because those are ADDITIONAL tests. You can still get the conventional PCR tests number to compare with.

**Comment by matejdro** [comment]
I realized now that PCR numbers are also not comparable, since existence of HAT tests caused people to use the HAT tests instead of going to the PCR. This would probably not be that good idea.
