### ISSUE TITLE
Remove whitespace from top of stats page

### ISSUE THREAD

**Issue by UrbanKocmut** [sledilnik/website#780]
Currently there is a big empty space in the last row of the number cards. I find this annoying.

I propose that all cards are made thinner so that there are 4 columns instead of the current 3. This would remove the last row with only 1 card.

![image](https://user-images.githubusercontent.com/22871708/103305104-967f8500-4a0a-11eb-9d0e-203186d8d3fa.png)

**Comment by lukarenko** [comment]
We might try, but we may introduce new cards soon (vacination)...

**Comment by UrbanKocmut** [comment]
Adding new cards would also solve this problem. Please close the issue when the whitespace is filled. Doesn't matter how.

**Comment by stefanb** [comment]
Improved via https://github.com/sledilnik/website/pull/782
