### ISSUE TITLE
Regions chart: add button to switch off all regions

### ISSUE THREAD

**Issue by majazaloznik** [sledilnik/website#791]
Often the user is only interested in one or only a few regions. 

Right now they have to click on each of the region buttons to turn then off.

A button to allow easy switching on and off of all regions would make the user experience much more pleasant :)

Proposed button label: "Vse regije"

**Comment by lukarenko** [comment]
@miaerbus we also need this for MetricsComparison chart.

This is past issue on this topic: https://github.com/sledilnik/website/issues/230

I would have Select All / Select None, but we need different design language to separate them from metrics itself. I think Jure Sobočan already gave some suggestion for icons.

**Comment by lukarenko** [comment]
I think Show All/Show None is already providing that functionality, so I do not see much benefit in two buttons.
