### ISSUE TITLE
Remove unneeded syringe icon

### ISSUE THREAD

**Issue by UrbanKocmut** [sledilnik/website#807]
I think that cards should be consistent and there is no need for a syringe icon in one card whereas other cards don't have an icon.
My complaint is only with the icon next to the large number indicating the current state and not the smaller one indicating the increase.

I reccomend that you remove the top icon and then have only one icon next to the lower number (green)

![slika](https://user-images.githubusercontent.com/22871708/105614644-e31c6d00-5dca-11eb-947c-5dc147dbc6f5.png)

**Comment by UrbanKocmut** [comment]
I see that I probably misunderstood the icons. The icons represent the number of vaccine shots people have got. I would therefore reccomend to have the lower number be black as other green numbers indicate change and in this case the number doesn't do this.

**Comment by lukarenko** [comment]
Yes, this is 1. and 2. dose. But you are right that we probably need on-hover tooltip or description on click, to explain

**Comment by lukarenko** [comment]
This was not changed to Vaccinated and Fully Vaccinated
