### ISSUE TITLE
Translation preview links invalid

### ISSUE THREAD

**Issue by retro65** [sledilnik/website#884]
The preview page linked to on the Russian translation is no longer valid, and it appears the same for a bunch of others too. (e.g. Montenegrin, Norwegian, and Albanian) The valid link appears to be https://pr-341.preview.sledilnik.org/ru/stats

I apologize for any misunderstanding on my side.

**Comment by retro65** [comment]
Also, the name of the language as it does appear on the preview page is "Руски", which is incorrect, and there doesn't seem to be a translation string for it.

**Comment by retro65** [comment]
Finally, what is the minimum required progress on a translation for it to be approved for the main site?

**Comment by stefanb** [comment]
Thanks for the notification, I have updated the preview links on https://hosted.weblate.org/projects/sledilnik/website/ru/ and other project languages.

**Comment by stefanb** [comment]
The Russian language was indeed missing in the source, fixed via e92859d.
It can now be translated in weblate: https://hosted.weblate.org/translate/sledilnik/website/ru/?checksum=25e2fa88889886fb

**Comment by stefanb** [comment]
As for the minimum required percentage there is no specific rule, but currently all languages used in production have above 80% (lowest is german with 81%).

We could start with a bit lower % with major elements of the homepage translated, if that would help attracting other Russian translators to reach 80+% and maintaining it there as new functionalities are added.

**Comment by retro65** [comment]
I was able to fix this mildly annoying goof now, thanks for the help & info!
