### ISSUE TITLE
Vaccinations graph shows wrong data on phone screen-size

### ISSUE THREAD

**Issue by lukaw3d** [sledilnik/website#927]
To reproduce;
- Android Chrome on phone screen width 1080px or Desktop Chrome window width <500px
- Find vaccinations graph (Cepljenje)
- Select date range: all (Obdobje: vse)
- See 5 million Slovenians vaccinated. ??

| narrow window | wider window |
| --- | --- |
| ![covid-19 sledilnik org_sl_stats (2)](https://user-images.githubusercontent.com/3758846/122299678-97e03380-cefe-11eb-995b-e7298a5105c2.png) | ![covid-19 sledilnik org_sl_stats (3)](https://user-images.githubusercontent.com/3758846/122299682-99a9f700-cefe-11eb-9504-9fd48d4fda4f.png) |

**Comment by stefanb** [comment]
Looks like Highcharts performs column aggregation on narrow screens, leading to these bizarre numbers
https://www.highcharts.com/forum/viewtopic.php?t=41411

**Comment by lukarenko** [comment]
@stefanb can you reproduce this? I was unable to reproduce it.

**Comment by lukaw3d** [comment]
Try running `open('https://covid-19.sledilnik.org/embed.html#/sl/chart/Vaccination', 'popup1', 'width=400,height=400')` + click `Obdobje: vse`

**Comment by stefanb** [comment]
Yes, I did see that problem too.

**Comment by stefanb** [comment]
Just now on the phone:
![Screenshot_20210622-210233](https://user-images.githubusercontent.com/319826/122984466-52f44b00-d39d-11eb-94b1-9c60678f0b05.jpg)

**Comment by stefanb** [comment]
Preview of fix via #947 available at:
https://pr-947.preview.sledilnik.org/
